version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: nest-api-project
    build:
      context: ./
    image: nest-api-project
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: nest_api_project
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local